version: '3.5'
services:
  automation-worker:
    container_name: automation-worker
    build:
      context: .
      dockerfile: docker/automation-worker/Dockerfile
    depends_on:
      - selenium-hub
    command: ["./scripts/wait-for-it.sh", "selenium-hub:4444", "--", "./scripts/run_unittest.sh"]
    tty: true
    volumes:
      - ./testcases:/sango/testcases
    env_file:
      - .env
    networks:
      - app-network
    ports:
      - 8081:8081

  selenium-hub:
    image: selenium/hub:3.141.59-20200409
    container_name: selenium-hub
    networks:
      - app-network
    ports:
      - "4444:4444"

  chrome:
    image: selenium/node-chrome:3.141.59-20200409
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    networks:
      - app-network
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444

networks:
  app-network:
    driver: bridge
